project_id = "bcmhhowvzopfbaudwkjl"

[functions.send-stuck-user-reminders]
verify_jwt = false
schedule = "0 9 * * *"

[functions.send-vault-starter-emails]
verify_jwt = false
schedule = "0 9 * * *"

[functions.unsubscribe-emails]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false